### ISSUE TITLE
DOC: Improve the CLI documentation rendering

### ISSUE THREAD

**Issue by jhlegarreta** [dipy/dipy#2665]
## Description

The positional arguments in the CLI documentation are not rendered in such a way that facilitates the reading; contrary to the optional argument list, where the argument name, type and docstring are clearly distinguished, the positional argument documentation elements are all rendered on the same line, with no formatting, e.g.
https://dipy.org/documentation/1.5.0/reference_cmd/dipy_fit_dti/#positional-arguments
https://dipy.org/documentation/1.5.0/reference_cmd/dipy_align_affine/#positional-arguments

Also, it looks like for some argument types, like `bool` (or `boolean`) or a list/tuple or variable length, the rendering does also change or the type is not put (in the case of booleans), and affects the subsequent argument docstring rendering, e.g.
`save_metrics` in [`dipy_fit_dti`](https://dipy.org/documentation/1.5.0/reference_cmd/dipy_fit_dti/#optional-arguments)
`level_iters` in [`dipy_align_affine`](https://dipy.org/documentation/1.5.0/reference_cmd/dipy_align_affine#optional-arguments)
`progressive` in [`dipy_align_affine`](https://dipy.org/documentation/1.5.0/reference_cmd/dipy_align_affine#optional-arguments)

## Way to reproduce

See
https://dipy.org/documentation/1.5.0/reference_cmd/dipy_fit_dti
![dipy_fit_dti_doc](https://user-images.githubusercontent.com/5576557/198140593-d1005364-abb7-4244-adf0-9545c0a04301.png)

Or
https://dipy.org/documentation/1.5.0/reference_cmd/dipy_align_affine
![dipy_align_affine_doc](https://user-images.githubusercontent.com/5576557/198140614-bdc159e1-8c68-41a7-be43-f795b05585d1.png)

**Comment by skoudoro** [comment]
Thank you the feedback @jhlegarreta.

I suppose our css is failing. 

However I plan to change this system and update the balance between django and static website. This should fix this issue.

**Comment by sammyboi1801** [comment]
Hey, it seems like this issue has still not been fixed. Can you assign this issue to me?

**Comment by jhlegarreta** [comment]
@sammyboi1801 Thanks for the interest in contributing to DIPY. You can go ahead and work on the fix, and then open a PR that will automatically close the issue; there is no strict need to have an issue assigned to contribute to the toolkit.

If an issue is assigned to somebody and a fix is not proposed within a reasonable time, it is perfectly fine to somebody else to take over without assigning the issue. The time invested in managing the assignments can be saved if a fix is ready and proposed in a PR. We are proud to receive contributions from anybody keen on the open source scientific computing community.

Let us you if you find difficulties in proposing a fix/opening a PR.

**Comment by sammyboi1801** [comment]
Hey, thanks a lot for replying. I had one doubt.
Since the issue seems to be in the website, am I right to assume that the source code will be found under the dipy_web repository?

**Comment by skoudoro** [comment]
if it is really a css issue, yes, you have to lookat dipy_web.  if it is a command line issue, you need to look at the documentation here @sammyboi1801

**Comment by shilpiprd** [comment]
Hi! I'd like to work on this issue but I can't find the html pages of the documentation. I've looked in dipy_web but it doesn't have these document pages. Could anyone please guide me as to where I can find the required document pages or if it 
even is in HTML format.

**Comment by jhlegarreta** [comment]
@shilpiprd the documentation is generated using [Sphinx](https://www.sphinx-doc.org/en/master/): the docstrings and `*.rst` files existing in the source code are processed by Sphinx to generate the HTML files that are rendered in our browsers.

The DIPY workflows dwell in [this folder](https://github.com/dipy/dipy/tree/master/dipy/workflows), and as an example, the DTI reconstruction workflow (`dipy_fit_dti`) documentation can be found [here](https://github.com/dipy/dipy/blob/master/dipy/workflows/reconst.py#L221).

**Comment by skoudoro** [comment]
done in #3348, closing
